/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsPreschoolLearningCardsRouteImport } from './routes/products.preschool-learning-cards'
import { Route as ProductsInteractiveBusyBookRouteImport } from './routes/products.interactive-busy-book'
import { Route as ProductsFingerPaintingKitRouteImport } from './routes/products.finger-painting-kit'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicOrderNotifyRouteImport } from './routes/api/public/order-notify'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPreschoolLearningCardsRoute =
  ProductsPreschoolLearningCardsRouteImport.update({
    id: '/products/preschool-learning-cards',
    path: '/products/preschool-learning-cards',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsInteractiveBusyBookRoute =
  ProductsInteractiveBusyBookRouteImport.update({
    id: '/products/interactive-busy-book',
    path: '/products/interactive-busy-book',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsFingerPaintingKitRoute =
  ProductsFingerPaintingKitRouteImport.update({
    id: '/products/finger-painting-kit',
    path: '/products/finger-painting-kit',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrderNotifyRoute = ApiPublicOrderNotifyRouteImport.update({
  id: '/api/public/order-notify',
  path: '/api/public/order-notify',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/order-success': typeof OrderSuccessRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/products/finger-painting-kit': typeof ProductsFingerPaintingKitRoute
  '/products/interactive-busy-book': typeof ProductsInteractiveBusyBookRoute
  '/products/preschool-learning-cards': typeof ProductsPreschoolLearningCardsRoute
  '/api/public/order-notify': typeof ApiPublicOrderNotifyRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/order-success': typeof OrderSuccessRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/products/finger-painting-kit': typeof ProductsFingerPaintingKitRoute
  '/products/interactive-busy-book': typeof ProductsInteractiveBusyBookRoute
  '/products/preschool-learning-cards': typeof ProductsPreschoolLearningCardsRoute
  '/api/public/order-notify': typeof ApiPublicOrderNotifyRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/order-success': typeof OrderSuccessRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/products/finger-painting-kit': typeof ProductsFingerPaintingKitRoute
  '/products/interactive-busy-book': typeof ProductsInteractiveBusyBookRoute
  '/products/preschool-learning-cards': typeof ProductsPreschoolLearningCardsRoute
  '/api/public/order-notify': typeof ApiPublicOrderNotifyRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/order-success'
    | '/email/unsubscribe'
    | '/products/finger-painting-kit'
    | '/products/interactive-busy-book'
    | '/products/preschool-learning-cards'
    | '/api/public/order-notify'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/order-success'
    | '/email/unsubscribe'
    | '/products/finger-painting-kit'
    | '/products/interactive-busy-book'
    | '/products/preschool-learning-cards'
    | '/api/public/order-notify'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/order-success'
    | '/email/unsubscribe'
    | '/products/finger-painting-kit'
    | '/products/interactive-busy-book'
    | '/products/preschool-learning-cards'
    | '/api/public/order-notify'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ProductsFingerPaintingKitRoute: typeof ProductsFingerPaintingKitRoute
  ProductsInteractiveBusyBookRoute: typeof ProductsInteractiveBusyBookRoute
  ProductsPreschoolLearningCardsRoute: typeof ProductsPreschoolLearningCardsRoute
  ApiPublicOrderNotifyRoute: typeof ApiPublicOrderNotifyRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/preschool-learning-cards': {
      id: '/products/preschool-learning-cards'
      path: '/products/preschool-learning-cards'
      fullPath: '/products/preschool-learning-cards'
      preLoaderRoute: typeof ProductsPreschoolLearningCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/interactive-busy-book': {
      id: '/products/interactive-busy-book'
      path: '/products/interactive-busy-book'
      fullPath: '/products/interactive-busy-book'
      preLoaderRoute: typeof ProductsInteractiveBusyBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/finger-painting-kit': {
      id: '/products/finger-painting-kit'
      path: '/products/finger-painting-kit'
      fullPath: '/products/finger-painting-kit'
      preLoaderRoute: typeof ProductsFingerPaintingKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/order-notify': {
      id: '/api/public/order-notify'
      path: '/api/public/order-notify'
      fullPath: '/api/public/order-notify'
      preLoaderRoute: typeof ApiPublicOrderNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ProductsFingerPaintingKitRoute: ProductsFingerPaintingKitRoute,
  ProductsInteractiveBusyBookRoute: ProductsInteractiveBusyBookRoute,
  ProductsPreschoolLearningCardsRoute: ProductsPreschoolLearningCardsRoute,
  ApiPublicOrderNotifyRoute: ApiPublicOrderNotifyRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
